-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: /home/dan/.cache/wal/colors-hyprland — convert this file to Lua and ensure it is on Lua's package.path.
require("~/.cache/wal/colors-hyprland.lua")

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60",
    position = "auto",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@120",
    position = "auto",
    scale = "1",
})

-- Workspace-monitor layout
hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1",
})


-- Peaclock pos/size layout
hl.window_rule({
    name = "conf-kitty-clock",
    match = { class = "kitty-clock" },
    float = true,
    pin = true,
    size = { "monitor_w * 0.18", "monitor_h * 0.155" },
    move = { "monitor_w - window_w - 6", "monitor_h - window_h - 80" },
    border_color = "rgba(787878DD) rgba(323232AA)",
})

-- Sound mixer pos/size layout
hl.window_rule({
    name = "conf-kitty-pulsemixer",
    match = { class = "kitty-pulsemixer" },
    float = true,
    size = { "monitor_w * 0.4", "monitor_h * 0.25" },
    move = { "monitor_w * 0.3", "monitor_h * 0.7" },
    border_color = "rgba(787878DD) rgba(323232AA)",
})

-- Taskbar pos/size layout 
hl.window_rule({
    name = "conf-kitty-taskbar",
    match = { class = "kitty-taskbar" },
    float = true,
    size = { "monitor_w * 0.28", "monitor_h * 0.84" },
    move = { "monitor_w * 0.03", "monitor_h * 0.08" },
    border_color = "rgba(787878DD) rgba(323232AA)",
})

-- Dropterm pos/size layout
hl.window_rule({
    name = "conf-kitty-dropterm",
    match = { class = "kitty-dropterm" },
    float = true,
    size = { "monitor_w * 0.7",  "monitor_h * 0.6" },
    move = { "monitor_w * 0.15", "monitor_h * 0.05" },
    border_color = "rgba(787878DD) rgba(323232AA)",
})


local terminal = "kitty"
local fileManager = "thunar"
-- $menu = wofi --show drun -n
local menu = "wofi -n"
local bluetooth = "blueman-manager"
--exec-once = hyprpaper
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "12")

hl.curve("fluid", { type = "bezier", points = { { 0.15, 0.85 }, { 0.25, 1 } } })
hl.curve("snappy", { type = "bezier", points = { { 0.3, 1 }, { 0.4, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3,
    bezier = "fluid",
    style = "popin 5%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 2.5,
    bezier = "snappy",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 4,
    bezier = "snappy",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.7,
    bezier = "snappy",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 4,
    bezier = "fluid",
    style = "slidefadevert -35%",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 2,
    bezier = "snappy",
    style = "popin 70%",
})
hl.device({
    name = "epic-mouse-v1",
    sensitivity = 0,
})

local mainMod = "SUPER"
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(bluetooth))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + CTRL + P", hl.dsp.window.pin())

hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + K", hl.dsp.layout("swapsplit"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

-- Изменение окон
hl.bind(mainMod .. " + U", hl.dsp.window.resize({ x = 30,  y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + Y", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })

hl.bind(mainMod .. " + CTRL + V", hl.dsp.exec_cmd("code"))
hl.bind(mainMod .. " + CTRL + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + right", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + left", hl.dsp.focus({ workspace = -1 }))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("ALT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind("ALT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("ALT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind("ALT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m region -o ~/Screenshots/"))
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m window -o ~/Screenshots/"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("hyprshot -m active -m output -o ~/Screenshots/"))
hl.bind(mainMod .. " + l", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
hl.bind("ALT + TAB", hl.dsp.exec_cmd("wlogout -b 2"))
hl.bind("ALT + w", hl.dsp.exec_cmd("~/.config/hypr/wallpaper.sh"))
hl.bind("ALT + a", hl.dsp.exec_cmd("~/.config/waybar/scripts/refresh.sh"))
hl.bind("ALT + B", hl.dsp.exec_cmd("~/.config/waybar/scripts/select.sh"))
hl.bind("ALT + r", hl.dsp.exec_cmd("~/.config/swaync/refresh.sh"))
hl.bind(mainMod .. " + M", hl.dsp.exit())

-- Pypr keybinds
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("pypr toggle term"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("pypr toggle music"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("pypr toggle taskbar"))
hl.bind(mainMod .. " + CTRL + T", hl.dsp.exec_cmd("kitty --class kitty-clock -e peaclock"))

hl.layer_rule({
    match = { namespace = "match:namespace ^(waybar)$" },
    blur = true,
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = { namespace = "match:namespace ^(waync-control-center)$" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "match:namespace ^(swaync-notification-window)$" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "match:namespace ^(swaync-control-center)$" },
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = { namespace = "match:namespace ^(swaync-notification-window)$" },
    ignore_alpha = 0.5,
})

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 5,
        border_size = 2,
        col = {
            active_border = "rgba(787878DD)",
            inactive_border = "rgba(323232AA)",
        },
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
    },
    decoration = {
        rounding = 0,
        active_opacity = 0.78,
        inactive_opacity = 0.7,
        fullscreen_opacity = 1,
        blur = {
            enabled = true,
            size = 3,
            passes = 5,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            popups = true,
        },
        shadow = {
            enabled = true,
            range = 15,
            render_power = 5,
            color = "rgba(0,0,0,.5)",
        },
    },
    animations = {
        enabled = true,
    },
    dwindle = {
        preserve_split = true,
    },
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo = true,
        focus_on_activate = true,
    },
    input = {
        kb_layout = "us,ru",
        follow_mouse = 1,
        sensitivity = 0,
        accel_profile = "flat",
        touchpad = {
            natural_scroll = true,
        },
        kb_options = "grp:alt_shift_toggle",
    },
    gestures = {
        --workspace_swipe = true
        workspace_swipe_distance = 300,
        workspace_swipe_cancel_ratio = .05,
        workspace_swipe_min_speed_to_force = 0,
    },
    -- bind = $mainMod, V, exec, hyprctl --batch "dispatch togglefloating; dispatch resizeactive exact 800 800; dispatch centerwindow 1;"
    --bind = CTRL, ESCAPE, exec, gksu #Dont worry about this
    --layerrule = ignorealpha 0.5, waybar
    --layerrule = ignorezero, swaync-control-center
    --layerrule = ignorezero, swaync-notification-window
    --layerrule = noanim, selection
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("sleep .5 && swww restore")
    hl.exec_cmd("swaync")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("swaync-client -df")
    hl.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 0")
    hl.exec_cmd("pypr")
end)

